/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zaposleni.ui;

import java.awt.Color;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import zaposleni.entity.Zaposleni;
import zaposleni.util.NewHibernateUtil;

/**
 *
 * @author djordje
 */
public class BrisanjeFrame extends javax.swing.JFrame {

    /**
     * Creates new form BrisanjeFrame
     */
    public BrisanjeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        povratakBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idTf = new javax.swing.JTextField();
        imeTf = new javax.swing.JTextField();
        godineTf = new javax.swing.JTextField();
        adresaTf = new javax.swing.JTextField();
        dohodakTf = new javax.swing.JTextField();
        idBtn = new javax.swing.JButton();
        imeBtn = new javax.swing.JButton();
        godineBtn = new javax.swing.JButton();
        adresaBtn = new javax.swing.JButton();
        dohodakBtn = new javax.swing.JButton();
        prikazBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rezultatLbl = new javax.swing.JLabel();
        rezTa = new javax.swing.JScrollPane();
        rezultatTa = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Brisanje zaposlenih");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 59, 70));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "    Zaposleni:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10), new java.awt.Color(196, 223, 230))); // NOI18N

        tabela.setBorder(null);
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        povratakBtn.setBackground(new java.awt.Color(126, 103, 94));
        povratakBtn.setForeground(java.awt.Color.white);
        povratakBtn.setText("Povratak u Meni");
        povratakBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                povratakBtnActionPerformed(evt);
            }
        });

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("ID zaposlenog");

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Ime i prezime");

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Godine");

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Adresa");

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Dohodak");

        idBtn.setBackground(new java.awt.Color(126, 103, 94));
        idBtn.setForeground(java.awt.Color.white);
        idBtn.setText("Obriši");
        idBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idBtnActionPerformed(evt);
            }
        });

        imeBtn.setBackground(new java.awt.Color(126, 103, 94));
        imeBtn.setForeground(java.awt.Color.white);
        imeBtn.setText("Obriši");
        imeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imeBtnActionPerformed(evt);
            }
        });

        godineBtn.setBackground(new java.awt.Color(126, 103, 94));
        godineBtn.setForeground(java.awt.Color.white);
        godineBtn.setText("Obriši");
        godineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                godineBtnActionPerformed(evt);
            }
        });

        adresaBtn.setBackground(new java.awt.Color(126, 103, 94));
        adresaBtn.setForeground(java.awt.Color.white);
        adresaBtn.setText("Obriši");
        adresaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresaBtnActionPerformed(evt);
            }
        });

        dohodakBtn.setBackground(new java.awt.Color(126, 103, 94));
        dohodakBtn.setForeground(java.awt.Color.white);
        dohodakBtn.setText("Obriši");
        dohodakBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dohodakBtnActionPerformed(evt);
            }
        });

        prikazBtn.setBackground(new java.awt.Color(126, 103, 94));
        prikazBtn.setForeground(java.awt.Color.white);
        prikazBtn.setText("Prikaz svih zaposlenih");
        prikazBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prikazBtnActionPerformed(evt);
            }
        });

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("*");

        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("*");

        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("*");

        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("*");

        jLabel10.setFont(new java.awt.Font("Noto Sans", 0, 10)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("* brisanje svih zaposlenih sa navedenom vrednošću");

        rezultatLbl.setForeground(java.awt.Color.white);

        rezTa.setEnabled(false);

        rezultatTa.setBackground(new java.awt.Color(133, 147, 174));
        rezultatTa.setColumns(20);
        rezultatTa.setForeground(java.awt.Color.white);
        rezultatTa.setRows(5);
        rezultatTa.setAutoscrolls(false);
        rezultatTa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rezTa.setViewportView(rezultatTa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(povratakBtn)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idTf)
                                    .addComponent(imeTf)
                                    .addComponent(godineTf)
                                    .addComponent(adresaTf)
                                    .addComponent(dohodakTf, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idBtn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(imeBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(adresaBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dohodakBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(godineBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addGap(56, 56, 56)
                                        .addComponent(rezultatLbl))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addComponent(rezTa, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(prikazBtn)
                                .addGap(168, 168, 168)
                                .addComponent(jLabel10)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idBtn))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(imeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imeBtn)
                            .addComponent(jLabel6)))
                    .addComponent(rezTa, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(godineTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(godineBtn)
                    .addComponent(jLabel7)
                    .addComponent(rezultatLbl))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(adresaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adresaBtn)
                    .addComponent(jLabel8))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dohodakTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dohodakBtn)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(povratakBtn)
                    .addComponent(prikazBtn)
                    .addComponent(jLabel10))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // HQL
    
    private void prikaziRezultat(List listaRezultata) {
        Vector<String> nasloviKolona = new Vector<>();
        Vector podaci = new Vector();
        
        nasloviKolona.add("ID");
        nasloviKolona.add("Ime i Prezime");
        nasloviKolona.add("Godine");
        nasloviKolona.add("Adresa");
        nasloviKolona.add("Dohodak");
        
        for(Object o : listaRezultata) {
            Zaposleni zaposleni = (Zaposleni)o;
            Vector<Object> red = new Vector<>();
            red.add(zaposleni.getZaposleni_id());
            red.add(zaposleni.getIme());
            red.add(zaposleni.getGodine());
            red.add(zaposleni.getAdresa());
            red.add(zaposleni.getDohodak());
            podaci.add(red);
        }
        
        tabela.setModel(new DefaultTableModel(podaci,nasloviKolona));
    }
    
    private void povratakBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_povratakBtnActionPerformed
        InitialFrame frame = new InitialFrame();
        frame.setSize(650,400);
        frame.getContentPane().setBackground(Color.decode("#8593ae"));
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_povratakBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            Session s = NewHibernateUtil.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery("from Zaposleni");
            List listaRezultata = q.list();
            prikaziRezultat(listaRezultata);
            s.getTransaction().commit();
            
        } catch (HibernateException e) {System.out.println("GRESKA! :" + e.getMessage());}
    }//GEN-LAST:event_formWindowOpened

    private void prikazBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prikazBtnActionPerformed
        try{
            Session s = NewHibernateUtil.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery("from Zaposleni");
            List listaRezultata = q.list();
            prikaziRezultat(listaRezultata);
            s.getTransaction().commit();
            
        } catch (HibernateException e) {System.out.println("GRESKA! :" + e.getMessage());}
    }//GEN-LAST:event_prikazBtnActionPerformed

    private void idBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idBtnActionPerformed
        try{
            Session s = NewHibernateUtil.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery("delete from Zaposleni z where z.zaposleni_id='"+idTf.getText()+"'");
            q.executeUpdate();
            
            s.getTransaction().commit();
            rezultatTa.setText("Zaposleni: \n ID: " + idTf.getText() + " uspesno obrisan");
            
        } catch (HibernateException e) {System.out.println("GRESKA! :" + e.getMessage());}
        
        idTf.setText("");
    }//GEN-LAST:event_idBtnActionPerformed

    private void imeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imeBtnActionPerformed
        try{
            Session s = NewHibernateUtil.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery("delete from Zaposleni z where z.ime='"+imeTf.getText()+"'");
            q.executeUpdate();
            s.getTransaction().commit();
            
            rezultatTa.setText("Zaposleni: \n Ime: " + imeTf.getText() + " uspesno obrisan");
            
        } catch (HibernateException e) {System.out.println("GRESKA! :" + e.getMessage());}
        
        imeTf.setText("");
    }//GEN-LAST:event_imeBtnActionPerformed

    private void godineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_godineBtnActionPerformed
        try{
            Session s = NewHibernateUtil.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery("delete from Zaposleni z where z.godine='"+godineTf.getText()+"'");
            q.executeUpdate();            
            s.getTransaction().commit();
            
            rezultatTa.setText("Zaposleni: \n Godine: " + godineTf.getText() + " uspesno obrisan");
            
        } catch (HibernateException e) {System.out.println("GRESKA! :" + e.getMessage());}
        
        godineTf.setText("");
    }//GEN-LAST:event_godineBtnActionPerformed

    private void adresaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresaBtnActionPerformed
        try{
            Session s = NewHibernateUtil.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery("delete from Zaposleni z where z.adresa='"+adresaTf.getText()+"'");
            q.executeUpdate();
            s.getTransaction().commit();
            
            rezultatTa.setText("Zaposleni: \n Adresa: " + adresaTf.getText() + " uspesno obrisan");
            
        } catch (HibernateException e) {System.out.println("GRESKA! :" + e.getMessage());}
        
        adresaTf.setText("");
    }//GEN-LAST:event_adresaBtnActionPerformed

    private void dohodakBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dohodakBtnActionPerformed
        try{
            Session s = NewHibernateUtil.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery("delete from Zaposleni z where z.dohodak='"+dohodakTf.getText()+"'");
            q.executeUpdate();            
            s.getTransaction().commit();
            
            rezultatTa.setText("Zaposleni: \n Dohodak: " + dohodakTf.getText() + " uspesno obrisan");
            
        } catch (HibernateException e) {System.out.println("GRESKA! :" + e.getMessage());}
        
        dohodakTf.setText("");
    }//GEN-LAST:event_dohodakBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrisanjeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrisanjeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrisanjeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrisanjeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrisanjeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adresaBtn;
    private javax.swing.JTextField adresaTf;
    private javax.swing.JButton dohodakBtn;
    private javax.swing.JTextField dohodakTf;
    private javax.swing.JButton godineBtn;
    private javax.swing.JTextField godineTf;
    private javax.swing.JButton idBtn;
    private javax.swing.JTextField idTf;
    private javax.swing.JButton imeBtn;
    private javax.swing.JTextField imeTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton povratakBtn;
    private javax.swing.JButton prikazBtn;
    private javax.swing.JScrollPane rezTa;
    private javax.swing.JLabel rezultatLbl;
    private javax.swing.JTextArea rezultatTa;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
