/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zaposleni.ui;

import java.awt.Color;

/**
 *
 * @author djordje
 */
public class InitialFrame extends javax.swing.JFrame {

    /**
     * Creates new form InitialFrame
     */
    public InitialFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        izmenaBtn = new javax.swing.JButton();
        unosBtn = new javax.swing.JButton();
        brisanjeBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hibernate Zaposleni Sistem");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Dobrodošli");

        jButton2.setBackground(new java.awt.Color(126, 103, 94));
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("Prikaz zaposlenih");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        izmenaBtn.setBackground(new java.awt.Color(126, 103, 94));
        izmenaBtn.setForeground(java.awt.Color.white);
        izmenaBtn.setText("Izmena podataka zaposlenih");
        izmenaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izmenaBtnActionPerformed(evt);
            }
        });

        unosBtn.setBackground(new java.awt.Color(126, 103, 94));
        unosBtn.setForeground(java.awt.Color.white);
        unosBtn.setText("Unos novih zaposlenih");
        unosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unosBtnActionPerformed(evt);
            }
        });

        brisanjeBtn.setBackground(new java.awt.Color(126, 103, 94));
        brisanjeBtn.setForeground(java.awt.Color.white);
        brisanjeBtn.setText("Brisanje zaposlenih");
        brisanjeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brisanjeBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 10)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Đorđe Gavrilović ITA16");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(izmenaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(unosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(brisanjeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(izmenaBtn)
                .addGap(18, 18, 18)
                .addComponent(unosBtn)
                .addGap(18, 18, 18)
                .addComponent(brisanjeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PrikazFrame frame = new PrikazFrame();
        frame.setSize(900,650);
        frame.getContentPane().setBackground(Color.decode("#8593ae"));
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void izmenaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izmenaBtnActionPerformed
        IzmenaFrame frame = new IzmenaFrame();
        frame.setSize(900,650);
        frame.getContentPane().setBackground(Color.decode("#8593ae"));
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_izmenaBtnActionPerformed

    private void unosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unosBtnActionPerformed
        UnosFrame frame = new UnosFrame();
        frame.setSize(900,650);
        frame.getContentPane().setBackground(Color.decode("#8593ae"));
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_unosBtnActionPerformed

    private void brisanjeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brisanjeBtnActionPerformed
        BrisanjeFrame frame = new BrisanjeFrame();
        frame.setSize(900,650);
        frame.getContentPane().setBackground(Color.decode("#8593ae"));
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_brisanjeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitialFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brisanjeBtn;
    private javax.swing.JButton izmenaBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton unosBtn;
    // End of variables declaration//GEN-END:variables
}
