/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zaposleni.ui;

import java.awt.Color;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import zaposleni.entity.Zaposleni;
import zaposleni.util.NewHibernateUtil;

/**
 *
 * @author djordje
 */
public class UnosFrame extends javax.swing.JFrame {

    /**
     * Creates new form UnosFrame
     */
    public UnosFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        povratakBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        imeTf = new javax.swing.JTextField();
        godineTf = new javax.swing.JTextField();
        adresaTf = new javax.swing.JTextField();
        dohodakTf = new javax.swing.JTextField();
        unosBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unos novih zaposlenih");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 59, 70));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "    Zaposleni:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10), new java.awt.Color(196, 223, 230))); // NOI18N

        tabela.setBorder(null);
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        povratakBtn.setBackground(new java.awt.Color(126, 103, 94));
        povratakBtn.setForeground(java.awt.Color.white);
        povratakBtn.setText("Povratak u Meni");
        povratakBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                povratakBtnActionPerformed(evt);
            }
        });

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Podaci o zaposlenom:");

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Ime i prezime");

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Godine");

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Adresa");

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Dohodak");

        unosBtn.setBackground(new java.awt.Color(126, 103, 94));
        unosBtn.setForeground(java.awt.Color.white);
        unosBtn.setText("Unesi");
        unosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unosBtnActionPerformed(evt);
            }
        });

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Svi podaci moraju biti uneti!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(unosBtn))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(imeTf)
                                    .addComponent(godineTf)
                                    .addComponent(adresaTf)
                                    .addComponent(dohodakTf, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(povratakBtn)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(152, 152, 152))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(imeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(godineTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(adresaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dohodakTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(povratakBtn)
                    .addComponent(unosBtn))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // HQL
    
    private void prikaziRezultat(List listaRezultata) {
        Vector<String> nasloviKolona = new Vector<>();
        Vector podaci = new Vector();
        
        nasloviKolona.add("ID");
        nasloviKolona.add("Ime i Prezime");
        nasloviKolona.add("Godine");
        nasloviKolona.add("Adresa");
        nasloviKolona.add("Dohodak");
        
        for(Object o : listaRezultata) {
            Zaposleni zaposleni = (Zaposleni)o;
            Vector<Object> red = new Vector<>();
            red.add(zaposleni.getZaposleni_id());
            red.add(zaposleni.getIme());
            red.add(zaposleni.getGodine());
            red.add(zaposleni.getAdresa());
            red.add(zaposleni.getDohodak());
            podaci.add(red);
        }
        
        tabela.setModel(new DefaultTableModel(podaci,nasloviKolona));
    }  
    
    private void povratakBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_povratakBtnActionPerformed
        InitialFrame frame = new InitialFrame();
        frame.setSize(650,400);
        frame.getContentPane().setBackground(Color.decode("#8593ae"));
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_povratakBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            Session s = NewHibernateUtil.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery("from Zaposleni");
            List listaRezultata = q.list();
            prikaziRezultat(listaRezultata);
            s.getTransaction().commit();
            
        } catch (HibernateException e) {System.out.println("GRESKA! :" + e.getMessage());}
    }//GEN-LAST:event_formWindowOpened

    private void unosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unosBtnActionPerformed
        try{
            Session s = NewHibernateUtil.getSessionFactory().openSession();
            s.beginTransaction();
            
            Zaposleni z = new Zaposleni();
            z.setIme(imeTf.getText());
            z.setGodine(Integer.valueOf(godineTf.getText()));
            z.setAdresa(adresaTf.getText());
            z.setDohodak(Integer.valueOf(dohodakTf.getText()));
            s.save(z);
            
            Query q = s.createQuery("from Zaposleni z where z.zaposleni_id='" + z.getZaposleni_id() + "'");
            List listaRezultata = q.list();
            prikaziRezultat(listaRezultata);
            
            s.getTransaction().commit();
            
            imeTf.setText("");
            godineTf.setText("");
            adresaTf.setText("");
            dohodakTf.setText("");
            
        } catch (HibernateException e) {System.out.println("GRESKA! :" + e.getMessage());}
    }//GEN-LAST:event_unosBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresaTf;
    private javax.swing.JTextField dohodakTf;
    private javax.swing.JTextField godineTf;
    private javax.swing.JTextField imeTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton povratakBtn;
    private javax.swing.JTable tabela;
    private javax.swing.JButton unosBtn;
    // End of variables declaration//GEN-END:variables
}
